version: '3.8'

services:
  api-ingestion:
    build: .
    container_name: opensky-api-ingestion
    environment:
      - STORAGE_ACCOUNT_NAME=stlogisticsplatform
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    command: python ingestion/api/opensky_ingestion.py
    restart: on-failure

  batch-ingestion:
    build: .
    container_name: shipment-batch-ingestion
    environment:
      - STORAGE_ACCOUNT_NAME=stlogisticsplatform
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
    command: python ingestion/batch/batch_ingestion.py
    restart: on-failure